version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./container_files/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - $REPORT_PATH:/tmp/share/reports
      - ./container_files/nginx/.htpasswd:/etc/nginx/conf.d/.htpasswd
    ports:
      - "8080:80"
    expose:
      - "80"
