{{- if and .Values.report.enabled .Values.report.auth.username .Values.report.auth.password }}
kind: Secret
apiVersion: v1
metadata:
  name: report-server-auth
  labels:
    app.kubernetes.io/name: report
    app.kubernetes.io/component: trustification
    app.kubernetes.io/part-of: trustification
data:
  .htpasswd: {{ (htpasswd .Values.report.auth.username .Values.report.auth.password) | b64enc | quote }}
{{ end }}
