{{- if and .Values.report.enabled }}
{{- $mod := dict "root" . "name" "report-server" "component" "report" "module" .Values.modules.reportServer -}}

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "trustification.common.name" $mod }}
  labels:
    {{- include "trustification.common.labels" $mod | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $mod.module.stateStorageSize | default "10Gi" | quote }}
{{end}}
