{{- if and .Values.report.enabled }}
{{- $mod := dict "root" . "name" "report-server" "component" "report" "module" .Values.modules.reportServer -}}
{{- include "trustification.ingress.defaultIngress" ( merge (deepCopy $mod) (dict
  "host" (include "trustification.host.report" $mod )
  "tlsMode" "edge"
))}}
{{- end }}
